import Head from "next/head";

const boards = [{ name: "Board 1", id: "1" }];

export default function Home() {
  return (
    <>
      <Head>
        <title>FusionPlanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto mt-6">
          <h1 className="text-4xl">Boards</h1>

          <ul>
            {boards.map(({ name, id }, index) => (
              <li key={index}>
                <a href={`/boards/${id}`}>{name}</a>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

